# Generated by Django 6.0.8 on 2026-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
    ]
